### PR TITLE
feature(newrelic): add optional newrelic integration

### PR DESCRIPTION
**Pull request by jrgm**
svcops would like to make use of New Relic. This PR just makes it possible to load the module if explicitly configured. Further configuration will happen with puppet in the circusd environment (unless we have to set so many switches that a sane configuration file makes sense).

r? @rfk 

/cc @ckolos

### CODE REVIEW

**Comment by jrgm** [comment]
Side note: I can't autocomplete anyone in svcops in this repo anymore (actually worse, it converts e.g., to @mozilla/cloudops-something-something)

**Comment by jrgm** [comment]
I added the svcops team to the teams setting. @ckolos is back.

**Comment by rfk** [comment]
r+ on the code, but I want to understand a little more about the implications of this.  I don't recall how invasive newrelic's data-gathering is, do we need to be worried about it slurping up email addresses and (hashed) passwords and other sensitive data?

**Comment by jrgm** [comment]
Yeah absolutely on  understanding implications. This will not go to production before that happens. This is to enable it in a place where we can work towards that understanding.

**Comment by ckolos** [comment]
@rfk  @jrgm https://docs.newrelic.com/docs/apm/transactions/transaction-traces/security-options-transaction-traces

**Pull request merged**
