### PR TITLE
fix(metrics): don't emit os_version if os_name is unset

### PR DESCRIPTION
**Pull request by philbooth**
Tangentially related to mozilla/fxa-amplitude-send#19.

Omits the `os_version` Amplitude property if we have no value for `os_name`, which is the same behaviour that I've implemented for the content server in mozilla/fxa-content-server#5587.

@davismtl does that seem like the right thing to do?

@mozilla/fxa-devs r?

### CODE REVIEW

**Comment by davismtl** [comment]
This makes sense to me. It should keep things cleaner.

My only thoughts are if we had OS and OS version as different properties then we wouldn't care.

**Comment by philbooth** [comment]
> My only thoughts are if we had OS and OS version as different properties then we wouldn't care.

@davismtl, they're different properties now fwiw: `os_name` and `os_version`. It's the Amplitude UI that combines them together as a single `OS` property.

**Comment by davismtl** [comment]
>> My only thoughts are if we had OS and OS version as different properties then we wouldn't care.
>@davismtl, they're different properties now fwiw: os_name and os_version. It's the Amplitude UI that combines them together as a single OS property.

Thanks for letting me know. Let's leave it as is for now. It's non-critical and I have workarounds up for now. We can look into adding os_name as it's own property in the future if it becomes more of a problem.

**Comment by philbooth** [comment]
> We can look into adding os_name as it's own property in the future if it becomes more of a problem.

I mean we're already emitting `os_name` and `os_version` as two separate properties, not sure if that was clear from what I wrote.

**Comment by davismtl** [comment]
Oh yes, I just looked at the API. Huh... I wonder why they merge them.

**Pull request merged**
