### PR TITLE
update fxa-auth-mailer/fxa-auth-db-mem in package.json and update shrinkwrap. 

### PR DESCRIPTION
**Pull request by jrgm**
Okay, cleaned this and dependent shrinkwraps up now. r? @chilts @dannycoates

### CODE REVIEW

**Comment by chilts** [comment]
"766 additions, 1,132 deletions not shown"

Looks fine to me! :) Well, the first commit does anyway.

I assume the 2nd is fine. I thought there used to be a button in the GitHub UI to be able to show a large diff (not that I would read a big diff of npm-shrinkwrap.json stuff anyway). r+

**Comment by dannycoates** [comment]
> I assume the 2nd is fine

note to self: hide all controversial changes in huge diff :wink:

**Comment by pdehaan** [comment]
@dannycoates Just start adding 1132 blank lines to the bottom of your files and apparently @chilts just automatically green lights the PR!

**Comment by chilts** [comment]
totally-awesome

**Pull request merged**
