### PR TITLE
feat(config): accept CORS requests from multiple origins

### PR DESCRIPTION
**Pull request by l-hedgehog**

### CODE REVIEW

**Comment by l-hedgehog** [comment]
Oops, not as minimal a change as I thought. I'll try to figure out what's wrong with the tests tomorrow morning.

**Comment by rfk** [comment]
Hi @l-hedgehog, is this ready for review from your point of view?  If so, please resolve the merge conflicts and re-push, and I'll add it to the coming dev cycle.

**Comment by l-hedgehog** [comment]
Yes. I'm out today and I'll update the PR tomorrow.

2016年5月30日星期一，Ryan Kelly <notifications@github.com> 写道：

**Comment by l-hedgehog** [comment]
In case it's not clear, this PR was rebased and re-pushed yesterday, and is ready for review from my point of view. Thanks.

**Comment by rfk** [comment]
This LGTM, thanks @l-hedgehog!

**Pull request merged**
