### PR TITLE
fix(config): Add imageUri for reference browser client-id

### PR DESCRIPTION
**Pull request by rfk**
Fixes https://github.com/mozilla/fxa-auth-server/issues/2726; @jrgm r?

### CODE REVIEW

**Comment by philbooth** [comment]
> Which is just delightful; I guess another maxmind db change leaking into tests?

That thing has an uncanny ability to break at the most inconvenient times. 😕

**Comment by shane-tomlinson** [comment]
> Which is just delightful; I guess another maxmind db change leaking into tests?

This is killing me. Can we stop asserting against a changing location?

**Comment by philbooth** [comment]
> Can we stop asserting against a changing location?

So I tried that once before, using an IP address I found for CERN, which had the location of Geneva. "Seems reasonable", I thought. Within a week it changed to some other place name.

**Comment by philbooth** [comment]
(which is not to say we can't do it, but finding a fixed location is surprisingly hard)

**Comment by shane-tomlinson** [comment]
> So I tried that once before, using an IP address I found for CERN, which had the location of Geneva. "Seems reasonable", I thought. Within a week it changed to some other place name.

This is terrible. Should we keep asserting the specific place? Could we just assert that *a* value is returned? Or keep an array of names that have popped up?

**Comment by philbooth** [comment]
> Could we just assert that *a* value is returned? Or keep an array of names that have popped up?

Yeah, I'm cool with either of these, with a mild preference for the latter. Good shout.

**Comment by philbooth** [comment]
> Could we just assert that *a* value is returned? Or keep an array of names that have popped up?

Ref: https://github.com/mozilla/fxa-auth-server/pull/2729

**Pull request merged**
