### PR TITLE
chore(shrinkwrap): get latest fxa-content-server-l10n version

### PR DESCRIPTION
**Pull request by jrgm**
Picks up subject lines and lockout strings.

### CODE REVIEW

**Comment by rfk** [comment]
Bumping dependencies for our dependencies in shrinkwrap, but not bumping the top-level dependency on fxa-auth-mailer....what fresh hell is this?  Is there a step missing in our train-cutting procedure?

**Comment by rfk** [comment]
Oh, also, r+

**Comment by dannycoates** [comment]
What do we need to do to fix this?

**Comment by rfk** [comment]
I guess we should be cuttng train versions of fxa-auth-mailer for this repo's trains to take as a dependency?

**Comment by jrgm** [comment]
> I guess we should be cuttng train versions of fxa-auth-mailer for this repo's trains to take as a dependency?

I don't think that would necessarily help, since shrinkwrap asserts versions from the top down.

> What do we need to do to fix this?

Maybe a scheme to move content-server-l10n out of the `node_modules` hierarchy, for example, as an npm postinstall 'git clone ...' by fxa-auth-server and pass the location to fxa-auth-mailer code </handwaving>

**Comment by jrgm** [comment]
Or, just make a fresh shrinkwrap part of `grunt version` (and rename to `grunt releasetasks` or something).

**Pull request merged**
