### PR TITLE
feat(recovery): WIP Delegated recovery testing

### PR DESCRIPTION
**Pull request by vbudhram**
Was experimenting with delegated recovery and wanted to put this up if others wanted to play around with it. Lots of work to be done...

Following steps at https://developers.facebook.com/docs/delegated-recovery/guide

### CODE REVIEW

**Comment by vladikoff** [comment]
@vbudhram it might make sense to branch this as `feature.*` so we can deploy this to a specific box

**Comment by vbudhram** [comment]
@vladikoff Just dawned on me that delegated recovery requires using private/public keys. Is it possible to copy those files into the docker image without checking them into source?

**Comment by vladikoff** [comment]
To discuss at a Tuesday server meeting

**Comment by vbudhram** [comment]
Closing this down for now.

**Pull request closed without merging**
