### PR TITLE
feat(hpkp): Add hpkp headers to all requests

### PR DESCRIPTION
**Pull request by vbudhram**
This adds the HPKP header to all requests.

Header:
```
Public-Key-Pins: max-age=2592000; includeSubDomains; pin-sha256="5kJvNEMw0KjrCAu7eXY5HZdvyCS13BbA0VJG1RSP91w="; pin-sha256="PZXN3lRAy+8tBKk2Ox6F7jIlnzr2Yzmwqc3JnyfXoCw="; pin-sha256="r/mIkG3eEpVdm+u/ko/cwxzOMo1bk4TyHIlByibiA5E=";
```

Ref: https://github.com/mozilla/fxa-bugzilla-mirror/issues/179

### CODE REVIEW

**Comment by vbudhram** [comment]
@jrgm @vladikoff This what you had in mind for hpkp headers?

**Comment by vbudhram** [comment]
@jrgm @vladikoff Mind an r? Thoughts on publishing hpkp hapi module for reuse?

**Comment by vladikoff** [comment]
> Thoughts on publishing hpkp hapi module for reuse?

I would say yes to this. Especially with the tests.

What would the usage be? 

Exactly like this?
```
if (config.hpkpConfig && config.hpkpConfig.enabled) {
 server.ext('onPreResponse', hpkp(config.hpkpConfig.max_age, config.hpkpConfig.pin_sha256,   config.hpkpConfig.includeSubDomains))
}
```

**Comment by vbudhram** [comment]
@vladikoff Yea that would be the exact usage, I will update!

**Comment by vbudhram** [comment]
Closing in favor of https://github.com/mozilla/fxa-auth-server/pull/1499

**Pull request closed without merging**
