### PR TITLE
feat(server): Log the `service` and `reason` parameters for `/account/login`.

### PR DESCRIPTION
**Pull request by shane-tomlinson**
@rfk - r?

This is the first step to determine the volume of notification emails that will be sent.

issue #875

### CODE REVIEW

**Comment by vladikoff** [comment]
@shane-tomlinson it seems this broke the functional test on the content server:
```
'unverified, acts like signup': function () {
```
Now the test times out, the second email never gets delivered 

https://github.com/mozilla/fxa-content-server/blob/a63443efa1abe7059bf1b74fbd1dfbc508dd79c2/tests/functional/oauth_sign_in.js#L182-L184

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson it seems this broke the functional test on the content server:

Huh, that's very strange. We don't actually *do* anything with the data. :/

**Comment by vladikoff** [comment]
@shane-tomlinson I rolled back to Release v1.37.0 so it can be any commit since that. Thought this was one suspicious

**Comment by vladikoff** [comment]
@shane-tomlinson nvm, 
```
7df36f4ff0c567792ff9d8c370b03f8ca836b7d4 is the first bad commit
commit 7df36f4ff0c567792ff9d8c370b03f8ca836b7d4
Author: Danny Coates <dannycoates@gmail.com>
Date:   Tue May 12 17:48:26 2015 -0700

    moar ENV
    
    This adds environment variable names for all config parameters. It
    also adds 'envc' to help make using them easier in dev and replaces
    the default json files. This is a baby step in configuring the
    process purely with the env which should make containerizing easier.

:000000 100644 0000000000000000000000000000000000000000 fa84c189613085445ee129d24d04daeefc46ce11 A	.env.dev
:040000 040000 9d88324423baae02feccd2a04e6162ad496e9512 7c0323401dc2f63e92d524a1470b8b313b6356a9 M	config
:100644 100644 6db010c847815595c03da53dd7fbfb2c8be0a8c0 00b7c81406ef244bb2001c784e9bf0270caf96d5 M	npm-shrinkwrap.json
:100644 100644 c82ec38db569d79206e7ee1404d6936a29bf6d5f c96e8d8e52eed6e17235070a9579c3351913864b M	package.json
:040000 040000 4171e3aa9fbe1c8dfeae47701dbdd4fbab076587 6bead7efca2f3ea99543daa3593799a3eeded4a2 M	test

```

**Comment by dannycoates** [comment]
@vladikoff it looks like you need to update the test server's config

**Comment by vladikoff** [comment]
@dannycoates sorry what should I update, is there a new email setting?

This is the restmail inbox (2 emails) before that change:
https://gist.github.com/vladikoff/10760376f0d7665c4895

After the change, we now only get 1 email: https://gist.github.com/vladikoff/58914d2580a296e8c3ad

**Comment by dannycoates** [comment]
@vladikoff I'm guessing you had `resendBlackoutPeriod` set somewhere. Config json files are no longer implicitly loaded, they require a `CONFIG_FILES` environment variable.

**Pull request merged**
