### PR TITLE
fix(config): Remove unused URL opions from mailer config.

### PR DESCRIPTION
**Pull request by rfk**
Connects to https://github.com/mozilla/fxa-auth-mailer/issues/203; @shane-tomlinson r?

### CODE REVIEW

**Comment by rfk** [comment]
Updating auth-mailer to see if that helps the test failures

**Comment by vbudhram** [comment]
Was shrinkwrap intended to be updated? Doesn't appear to be any update to modules.

**Comment by rfk** [comment]
That was just to get the latest auth-mailer for the tests, I'll undo it and see if they still pass...

**Comment by rfk** [comment]
Nope, definitely needs that change in order for the tests to pass; FWIW this is just pulling in the corresponding auth-mailer change for https://github.com/mozilla/fxa-auth-mailer/issues/203

**Comment by rfk** [comment]
I put the shrinkwrap update back; there's no corresponding change to package.json because that one references `fxa-auth-mailer#master` rather than a specific commit.

**Comment by vbudhram** [comment]
@rfk LGTM 👍 , merge at will!

**Pull request merged**
