### PR TITLE
feat(logging): Log hawk timestamp skew to statsd for easier analysis.

### PR DESCRIPTION
**Pull request by rfk**
We meant to do some analysis of this skew measurement, but haven't prioritized it.  Let's sent it to statsd/datadog for easier aggregation and analysis.  @jrgm r?

### CODE REVIEW

**Comment by jrgm** [comment]
I suppose it doesn't really matter which direction the skew is in, just the magnitude. So, if that's the metric you want, r+

**Comment by rfk** [comment]
>  it doesn't really matter which direction the skew is in

Indeed.  Actually I realized this is probably not accurately reflected as a "timing" metric and should be a generic histogram, but I'll keep it as abs() to make the aggregation statistics more reliable.

**Comment by rfk** [comment]
I redid this to use a histogram rather pretending it's a timer; @vladikoff mind a quick r? since IIRC you did much of the initial statsd stuff in this repo.

**Comment by vladikoff** [comment]
Nice :+1:

**Pull request merged**
