### PR TITLE
chore(deps): update to latest version of hapi

### PR DESCRIPTION
**Pull request by vladikoff**

### CODE REVIEW

**Comment by seanmonstar** [comment]
This also adds `inert`, which I didn't expect from a "update some dependencies" PR. What's the addition for?

**Comment by vladikoff** [comment]
this is blocked a bit by node 4

**Comment by vladikoff** [comment]
@rfk @vbudhram @seanmonstar r?

**Comment by seanmonstar** [comment]
r+ awesome!

**Comment by vbudhram** [comment]
LGTM 🎉

**Comment by rfk** [comment]
LGTM! 🎉

**Pull request merged**
