### PR TITLE
Remove datadog / statsd metrics reporting

### PR DESCRIPTION
**Pull request by sunakshi96**
refer #1611

### CODE REVIEW

**Comment by rfk** [comment]
Looks like the CI failures here:

  https://travis-ci.org/mozilla/fxa-auth-server/jobs/213752521

Are due to tests that check whether logging calls were performed correctly, e.g. the first one is checking that there were 10 calls to logging functions, but with your change here there are now only 8 calls.  I think it's reasonable to go through the failing tests and change the ones that now have incorrect numbers based on the changes here - let me know if you need any tips on interpreting the tracebacks in the test log to find the right locations.

@vladikoff, it looks like some of the reminders and push tests are depending on these `log.increment` calls to detect whether certain actions happened, we'll have to figure out a different strategy for doing those tests.

**Comment by sunakshi96** [comment]
@rfk yes I would like to  know how to interpret the tracebacks in the test log to find the right locations.

**Comment by rfk** [comment]
> I would like to know how to interpret the tracebacks in the test log to find the right locations.

Sorry for the delay in responding here, I got pulled into a little bit of a crisis in a different project :-(

Anyways, taking the first error from https://travis-ci.org/mozilla/fxa-auth-server/jobs/213752521 as an example:

```
  1) bounce messages should handle multiple recipients in turn:

      AssertionError: messages logged from assert.equal(mockLog.messages.length, 10, 'messages logged')

      + expected - actual

      -8

      +10

      

      at Function.insist [as equal] (node_modules/insist/insist.js:93:19)

      at test/local/email/bounce.js:75:16

      at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)

      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:510:31)

      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:567:18)

      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:612:10)

      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:691:18)

      at Async._drainQueue (node_modules/bluebird/js/release/async.js:133:16)

      at Async._drainQueues (node_modules/bluebird/js/release/async.js:143:10)

      at Immediate.Async.drainQueues [as _onImmediate] (node_modules/bluebird/js/release/async.js:17:14)
```

The important parts are:

* It mentions the file `test/local/email/bounce.js` and line 75.  In general, the files of interest for each error will be files under the "test" directory.
* The "-8" and "+10" part says that the test case was expecting log methods to be called 10 times, but they were only called 8 times.

I think it's fine to just adjust the  numbers in each test to match what's actually happening, e.g. for this one we'd just change "10" to "8".

**Comment by vladikoff** [comment]
Please rebase this Pull Request against the latest master branch. Let us know if you need help with that...

**Comment by rfk** [comment]
Closing in favour of https://github.com/mozilla/fxa-auth-server/pull/1921

**Pull request closed without merging**
