### PR TITLE
chore(ci): run tests on node 8

### PR DESCRIPTION
**Pull request by philbooth**
Think we agreed in the meeting to run them in 8 too?

@mozilla/fxa-devs r?

### CODE REVIEW

**Comment by philbooth** [comment]
Oh right, it's because they don't pass in node 8. Probably you guys tried this already, sorry.

**Comment by vladikoff** [comment]
@philbooth looks like only MySQL bit didn't pass, the install part?

**Comment by philbooth** [comment]
@vladikoff yep, not tried digging into the problem over in that repo yet, will do at some point.

**Comment by vladikoff** [comment]
👍

**Pull request closed without merging**
