### PR TITLE
chore(shrinkwrap): shrinkwrap with --dev, else missing prod-required modules - o_O

### PR DESCRIPTION
**Pull request by jrgm**

### CODE REVIEW

**Comment by jrgm** [comment]
npm ERR! missing: simplesmtp@~0.2 || ~0.3.30, required by nodemailer@0.7.1
npm ERR! missing: hawk@2.x.x, required by hapi-auth-hawk@2.0.0
npm ERR! missing: commander@^2.8.1, required by har-validator@2.0.2

Makes no sense. #npmwtf

**Comment by vladikoff** [comment]
>else missing prod-required modules - o_O

simeplesmtp, hawk and commander are all devDeps, should they be promoted to deps?

**Comment by jrgm** [comment]
They are entrained by prod modules:
```
hapi-auth-hawk -> hawk
fxa-auth-mailer -> nodemailer -> simplesmtp
request -> har-validator -> commander
```
`npm install --production`: Nice theory; doesn't work in practice.

**Comment by vladikoff** [comment]
> npm install --production: Nice theory; doesn't work in practice.

Hm it should work fine. I tried reproducing the npm issue using: 

```

  "name": "npm-shrinkwat",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "chalk": "1.1.1"
  },
  "devDependencies": {
    "ansi-styles": "2.1.0",
    "lodash": "3.10.1"
  }
}
```
where `ansi-styles` is a devDep and shrinkwrap worked as expected with npm 3.3.9

Result:
```
{
  "name": "npm-shrinkwat",
  "version": "1.0.0",
  "dependencies": {
    "ansi-regex": {
      "version": "2.0.0",
      "from": "ansi-regex@>=2.0.0 <3.0.0",
      "resolved": "https://registry.npmjs.org/ansi-regex/-/ansi-regex-2.0.0.tgz"
    },
    "ansi-styles": {
      "version": "2.1.0",
      "from": "ansi-styles@>=2.1.0 <3.0.0",
      "resolved": "https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.1.0.tgz"
    },
    "chalk": {
      "version": "1.1.1",
      "from": "chalk@1.1.1",
      "resolved": "https://registry.npmjs.org/chalk/-/chalk-1.1.1.tgz"
    },
    "escape-string-regexp": {
      "version": "1.0.3",
      "from": "escape-string-regexp@>=1.0.2 <2.0.0",
      "resolved": "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.3.tgz"
    },
    "has-ansi": {
      "version": "2.0.0",
      "from": "has-ansi@>=2.0.0 <3.0.0",
      "resolved": "https://registry.npmjs.org/has-ansi/-/has-ansi-2.0.0.tgz"
    },
    "strip-ansi": {
      "version": "3.0.0",
      "from": "strip-ansi@>=3.0.0 <4.0.0",
      "resolved": "https://registry.npmjs.org/strip-ansi/-/strip-ansi-3.0.0.tgz"
    },
    "supports-color": {
      "version": "2.0.0",
      "from": "supports-color@>=2.0.0 <3.0.0",
      "resolved": "https://registry.npmjs.org/supports-color/-/supports-color-2.0.0.tgz"
    }
  }
}
```

**Comment by jrgm** [comment]
> npm 3.3.9

Cool story bro.

**Pull request merged**
