### PR TITLE
fix(scripts): nicely stringify regexps when logging config

### LINKED ISSUE #1492: RegExp values display as `{}` in config printout at startup.
cc @philbooth

### PR DESCRIPTION
**Pull request by philbooth**
Fixes #1492.

@shane-tomlinson, as promised, this fixes the display of RegExp config settings on start-up. r?

### CODE REVIEW

**Comment by jrgm** [comment]
wtfjs!

**Comment by philbooth** [comment]
> wtfjs!

Ha ha, oh dear. Is it the one-letter argument names or comparing against `constructor` or the weird concatenation thing I've done that you find most objectionable? 😄

I'm happy to change it!

**Comment by philbooth** [comment]
Also, just to clarify what this actually fixes, this is taken from the log without the change applied:

```
"enabledEmailAddresses":{}
```

And this is taken from the log with the fix applied:

```
"enabledEmailAddresses":"/.+@mozilla\\.com$/"
```

Not perfect, but significantly more useful than the former.

**Comment by jrgm** [comment]
I was just referring to Javascript itself:
```
  JSON.stringify(/^foobar$/) => {}
  /^foobar$/.toString()      => '/^foobar$/'
```
which is, well, ...

**Comment by jrgm** [comment]
And I think your fix for this is fine ;-)

**Pull request merged**
