### PR TITLE
[train-34] some shrinkwrap and version cleanup from trunk that was intended to be part of train-34 too

### PR DESCRIPTION
**Pull request by jrgm**
I biffed and branched train-34 before the PR https://github.com/mozilla/fxa-auth-server/pull/904 was merged to master. I need these two commits on train-34 to have the correct l10n for email in this train. Mea culpa.

### CODE REVIEW

**Comment by pdehaan** [comment]
Travis failed.
Travis failed because of `grunt validate-shrinkwrap` (and vuln modules in restify and grunt-bump).

I think I'm OK with just adding a `--force` flag on that Travis command to get this passing would be OK (we do it in fxa-content-server repo). Then we can dig into bumping the deps in the various repos.

```
$ grunt validate-shrinkwrap
Running "validate-shrinkwrap" task
/home/travis/build/mozilla/fxa-auth-server/npm-shrinkwrap.json
>> Name    Installed  Patched  Vulnerable Dependency
>> semver    2.3.2    >=4.3.2  fxa-auth-server > fxa-auth-db-mem > fxa-auth-db-server > restify
>> semver    2.3.2    >=4.3.2  fxa-auth-server > fxa-auth-mailer > restify
>> semver    4.2.2    >=4.3.2  fxa-auth-server > grunt-bump
Warning: known vulnerable modules found Use --force to continue.
Aborted due to warnings.
The command "grunt validate-shrinkwrap" exited with 6.
Done. Your build exited with 1.
```

Ugh, looks like the [**semver**](https://nodesecurity.io/advisories/semver_redos) vuln above was just disclosed today.

Lets just `--force` this in travis to get it passing for this merge.

**Comment by jrgm** [comment]
So, put `--force` on this branch, to make those a warning.

**Comment by pdehaan** [comment]
@jrgm Possibly need to add it to _master_ as well, since this would seemingly break builds/Travis until **restify** and other modules get updated to latest **semver** module.

**Comment by pdehaan** [comment]
LGTM.
Verified the Git SHAs for fxa-auth-db-mem#master and fxa-auth-mailer#master both resolve to the latest commit SHAs for their respective repos.

**Pull request merged**
