### PR TITLE
fix(tests): fix test runner to exit with proper exit code

### LINKED ISSUE #1349: Builds with failing tests are passing in CI
Noticed this after pushing changes to a branch I'm working on. `npm test` fails but is followed by `npm run test-e2e`, which doesn't fail. The build status appears to be dictated by the result of that second job.

Example: https://travis-ci.org/mozilla/fxa-auth-server/jobs/145796037

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes #1349

### CODE REVIEW

**Comment by vladikoff** [comment]
@philbooth @vbudhram r?

**Comment by vbudhram** [comment]
Looks like there is an intermittent test failure? Does not fail for me locally and passes other CI test combinations.

```
test/local/verification_reminder_tests.js ............. 0/4

  creates reminders with valid options and rate

  not ok test unfinished: creates reminders with valid options and rate

    at:

      line: 32

      column: 1

      file: test/local/verification_reminder_tests.js

    source: |

      test(
```

**Comment by philbooth** [comment]
Boom! Here is a broken build to prove it works: https://travis-ci.org/mozilla/fxa-auth-server/builds/145829993

**Comment by vladikoff** [comment]
@vbudhram https://github.com/mozilla/fxa-auth-server/issues/1311 reopened this, will investigate, thanks!

**Pull request merged**
