### PR TITLE
chore(deps): use latest version of scrypt-hash package.

### LINKED ISSUE #854: fxa-auth-server installation fails
While I'm trying to install the fxa-auth-server I get this error message:

fxcloud@raspberrypi ~/fxa-auth-server $ npm install
 
> bigint@0.4.2 install /home/fxcloud/fxa-auth-server/node_modules/bigint
> node-gyp configure build

make: Entering directory '/home/fxcloud/fxa-auth-server/node_modules/bigint/build'
  CXX(target) Release/obj.target/bigint/bigint.o
  SOLINK_MODULE(target) Release/obj.target/bigint.node
  SOLINK_MODULE(target) Release/obj.target/bigint.node: Finished
  COPY Release/bigint.node
make: Leaving directory '/home/fxcloud/fxa-auth-server/node_modules/bigint/build'
 
> scrypt-hash@1.1.8 install /home/fxcloud/fxa-auth-server/node_modules/scrypt-hash
> node-gyp rebuild

make: Entering directory '/home/fxcloud/fxa-auth-server/node_modules/scrypt-hash/build'
  CC(target) Release/obj.target/scrypt/crypto_scrypt-sse.o
../crypto_scrypt-sse.c:33:23: fatal error: emmintrin.h: No such file or directory
compilation terminated.
scrypt.target.mk:92: recipe for target 'Release/obj.target/scrypt/crypto_scrypt-sse.o' failed
make: *** [Release/obj.target/scrypt/crypto_scrypt-sse.o] Error 1
make: Leaving directory '/home/fxcloud/fxa-auth-server/node_modules/scrypt-hash/build'
gyp ERR! build error 
ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.12.35+
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/fxcloud/fxa-auth-server/node_modules/scrypt-hash
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 
 
> dtrace-provider@0.3.0 install /home/fxcloud/fxa-auth-server/node_modules/bunyan/node_modules/dtrace-provider
> scripts/install.js

 
> dtrace-provider@0.2.8 install /home/fxcloud/fxa-auth-server/node_modules/fxa-auth-db-mem/node_modules/fxa-auth-db-server/node_modules/restify/node_modules/dtrace-provider
> node-gyp rebuild

make: Entering directory '/home/fxcloud/fxa-auth-server/node_modules/fxa-auth-db-mem/node_modules/fxa-auth-db-server/node_modules/restify/node_modules/dtrace-provider/build'
  TOUCH Release/obj.target/DTraceProviderStub.stamp
make: Leaving directory '/home/fxcloud/fxa-auth-server/node_modules/fxa-auth-db-mem/node_modules/fxa-auth-db-server/node_modules/restify/node_modules/dtrace-provider/build'
 
> browserid-crypto@0.7.0 postinstall /home/fxcloud/fxa-auth-server/node_modules/browserid-crypto
> node ./scripts/bundle.js

/
****Bundling VEP for Browser****

\
***Packaging External Dependencies****

 
> dtrace-provider@0.2.8 install /home/fxcloud/fxa-auth-server/node_modules/fxa-auth-mailer/node_modules/restify/node_modules/dtrace-provider
> node-gyp rebuild

make: Entering directory '/home/fxcloud/fxa-auth-server/node_modules/fxa-auth-mailer/node_modules/restify/node_modules/dtrace-provider/build'
  TOUCH Release/obj.target/DTraceProviderStub.stamp
make: Leaving directory '/home/fxcloud/fxa-auth-server/node_modules/fxa-auth-mailer/node_modules/restify/node_modules/dtrace-provider/build'
npm ERR! scrypt-hash@1.1.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the scrypt-hash@1.1.8 install script.
npm ERR! This is most likely a problem with the scrypt-hash package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls scrypt-hash
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.12.35+
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /home/fxcloud/fxa-auth-server
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

Anyone an idea, how I can fix this? Thanks.

OS: Raspbian GNU/Linux 7 \n \l
node v0.10.35
npm v2.1.18

### PR DESCRIPTION
**Pull request by rfk**
Fixes #854.

### CODE REVIEW

**Comment by dannycoates** [comment]
IDK if that scrypt-hash guy can be trusted :wink:

**Comment by rfk** [comment]
@dannycoates was that an r-? ;-)

**Comment by dannycoates** [comment]
#887 has the better diff

**Comment by rfk** [comment]
> #887 has the better diff

Hah, definitely can't argue with that :-)

**Pull request closed without merging**
