### PR TITLE
fix(links): use a custom url when verifying primary email

### PR DESCRIPTION
**Pull request by vbudhram**
To help keep our metrics sane, use a different url for verifying your primary email. https://github.com/mozilla/fxa-content-server/pull/5626 adds support for this view.

### CODE REVIEW

**Comment by vbudhram** [comment]
@mozilla/fxa-devs r?

**Comment by vbudhram** [comment]
@vladikoff Thanks!

**Comment by rfk** [comment]
Do we need to stage the rollout of this relative to #5626, so we can ensure the new route is available before we send the emails?

**Comment by vbudhram** [comment]
Don't think it would hurt to have this in train-99. It is fairly low risk since the feature won't ship until 100. Will do a point release.

**Pull request merged**
