### PR TITLE
Always check email case on login

### PR DESCRIPTION
**Pull request by rishibaldawa**
Fixes : https://github.com/mozilla/fxa-auth-server/issues/800

### CODE REVIEW

**Comment by rfk** [comment]
Thanks @rishibaldawa!

@dannycoates I recall discussing this with you a while back, do we have any particular reason to perform this chec either before or after the password check?  IIRC doing it before checking the password is better, since there's less risk of giving an attacker "free" password-guessing attempts by varying the case of the email.

**Comment by dannycoates** [comment]
Looks great! Thanks @rishibaldawa

> doing it before checking the password is better

Right. This will prevent using different email cases to get past the rate limiting.

**Comment by dannycoates** [comment]
I'll merge, but we should add a test case.

**Comment by rishibaldawa** [comment]
There seems to be already a test case https://github.com/mozilla/fxa-auth-server/blob/master/test/remote/account_login_tests.js#L39 

Am I looking at the wrong place ?

**Comment by dannycoates** [comment]
Yeah, its already covered. I was thinking we should have a test for "correct authPW, incorrect case" but since the case check happens first it doesn't matter.

**Comment by rishibaldawa** [comment]
Doesn't hurt. Lemme add that quick.

**Comment by rishibaldawa** [comment]
here's my recommended change : https://github.com/mozilla/fxa-auth-server/compare/master...rishibaldawa:master

Lemme know what you think.

**Comment by rishibaldawa** [comment]
Do you guys think its okay to close the issue? The current test already does the correct password, incorrect case test. Other than renaming, can't think of anything else left. Unless I'm missing something.

**Comment by rfk** [comment]
@rishibaldawa yep, I think it's good to go.  Thanks again!

**Pull request merged**
