### PR TITLE
fix(push): Add metrics events for reason=accountConfirm

### LINKED ISSUE #1496: TypeError: Cannot read property 'send'
When going to complete_signin on the content server I got this 

image

```
2|auth-ser | fxa-auth-server.INFO: request.summary {"op":"request.summary","code":200,"errno":0,"rid":"1475867247159:Vlads-MBP:50038:iu0586up:10017","path":"/v1/recovery_email/verify_code","lang":"en-US,en;q=0.8,da;q=0.6","agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36","remoteAddressChain":["127.0.0.1"],"t":8,"uid":"5c18783e443849bf81d6e56bac0d0050","service":"sync"}
2|auth-ser | fxa-auth-server.ERROR: console {"op":"console","message":"TypeError: Cannot read property 'send' of undefined\n    at /Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/lib/push.js:313:37\n    at bound (domain.js:287:14)\n    at runBound (domain.js:300:12)\n    at tryCatcher (/Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/node_modules/bluebird/js/main/util.js:26:23)\n    at ReductionPromiseArray._promiseFulfilled (/Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/node_modules/bluebird/js/main/reduce.js:105:38)\n    at ReductionPromiseArray.init (/Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/node_modules/bluebird/js/main/promise_array.js:92:18)\n    at ReductionPromiseArray.init (/Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/node_modules/bluebird/js/main/reduce.js:42:10)\n    at Async._drainQueue (/Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/node_modules/bluebird/js/main/async.js:128:12)\n    at Async._drainQueues (/Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/node_modules/bluebird/js/main/async.js:133:10)\n    at Immediate.Async.drainQueues [as _onImmediate] (/Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/node_modules/bluebird/js/main/async.js:15:14)\n    at processImmediate [as _immediateCallback] (timers.js:383:17)"}
2|auth-ser | fxa-auth-server.INFO: geodb.start {"op":"geodb.start","enabled":true,"dbPath":"/Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/node_modules/fxa-geodb/db/cities-db.mmdb"}
2|auth-ser | {"event":"config","data":{"env":"dev","geodb":{"dbPath":"/Users/vladik
```

The reason that is sent here `accountConfirm`.

```js
sendPush: function sendPush(uid, devices, reason, options) {
      options = options || {}
      var events = reasonToEvents[reason] 
      // ^ reasonToEvents has not have `accountConfirm` <<<<<<<<<<<<<<<<<

 
      // There's no spec-compliant way to error out as a result of having
      // too many devices to notify.  For now, just log metrics about it.
      if (devices.length > MAX_ACTIVE_DEVICES) {
        reportPushError(new Error(ERR_TOO_MANY_DEVICES), uid, null)
      }
      return P.each(devices, function(device) {
        var deviceId = device.id.toString('hex')

        log.trace({
          op: LOG_OP_PUSH_TO_DEVICES,
          uid: uid,
          deviceId: deviceId,
          pushCallback: device.pushCallback
        })

        if (device.pushCallback) {
          // send the push notification
          incrementPushAction(events.send)
```

We need to add a guard for the `events` var probably.

### PR DESCRIPTION
**Pull request by rfk**
Fixes #1496; @philbooth r?

### CODE REVIEW

**Comment by rfk** [comment]
We'll also need to backport this to train-71 release

**Comment by rfk** [comment]
actually @philbooth is PTO, @vbudhram or @seanmonstar any change you could take a quick look at this so we can include it in a patch to train-71?

**Comment by vbudhram** [comment]
@rfk Late to the game but r+!

**Comment by rfk** [comment]
I made a 71.2 tag with cherry-picked fix: https://github.com/mozilla/fxa-auth-server/releases/tag/v1.71.2

**Comment by philbooth** [comment]
Oh whoops, I caused this didn't I? Sorry everyone!

**Pull request merged**
