### PR TITLE
Add Docker support

### PR DESCRIPTION
**Pull request by mostlygeek**
Add a Dockerfile and a few tweaks so `npm test` passes. 
This is meant to build a container for deployment.

### CODE REVIEW

**Comment by vladikoff** [comment]
Is it possible to add some docs on how to use this? We have some stuff in other repos: https://github.com/mozilla/fxa-content-server#docker-based-development

**Comment by rfk** [comment]
It's also a little different from the existing docker stuff, which is targetting for using docker in a development flow rather than for deployment.  (And I thought we actually had that in this repo as well)

**Comment by mostlygeek** [comment]
The Dockerfile should be for creating a container for deployment.

For Dev, I assume the priority is getting something running and hackable.  A Vagrantfile is a better option as it runs in OSX/Windows/Linux.  You can edit the source on the host machine while running it in the VM (via a mount).

**Comment by mostlygeek** [comment]
@vladikoff this is the vision: 

- travis-ci would build the container via Dockerfile  and then run the tests
- ops would deploy the container. No more RPM building
- devs maintain the Dockerfile, which guarantees the app runs. No more dependency chasing due to ubuntu vs centos vs whatever.

Building the container would be (this is what op's jenkins does): 
````
$ docker build -t registry.hostname/mozilla/fxa-auth-server:sometag . 
````

**Comment by vladikoff** [comment]
Seems like a stale PR, let us know if a new version should be reviewed !

**Pull request closed without merging**
