### PR TITLE
switch from bunyan to mozlog

### LINKED ISSUE #879: replace bunyan with mozlog

### PR DESCRIPTION
**Pull request by dannycoates**
closes #879 

@jrgm and @whd this changes the log output to mozlog json format.

This also retires the `domain` tracing that hasn't been use for a while.

### CODE REVIEW

**Comment by rfk** [comment]
LGTM; @jrgm will this require corresponding fxa-dev and puppet-config PRs due to output format change?

**Comment by jrgm** [comment]
@rfk I think we'll want to change which filename to look in for content, and maybe for email bounce handling too. https://github.com/mozilla-services/puppet-config/blob/e8bebf3a72db9b1f1ae3ab139203b9ba1591f64b/fxa/modules/fxa/templates/data/fxa-auth-server/hekad.toml.erb#L13-L23. I don't think we need to modify fxa-dev. But I can handle both those after this lands. 

Otherwise, LGTM too.

**Comment by dannycoates** [comment]
Logs will continue to write to `stderr` until we change the account event mechanism, so the file ought to be the same.

**Comment by dannycoates** [comment]
Merging, we can revert if there's probs.

**Pull request merged**
