### PR TITLE
fix(tests): disable e2e tests until push server fixed

### PR DESCRIPTION
**Pull request by vladikoff**
Related to https://github.com/mozilla/fxa-auth-server/issues/1368

### CODE REVIEW

**Comment by vladikoff** [comment]
we discussed it on monday morning meeting, this is done to unblock other PRs for now.

**Comment by vbudhram** [comment]
👍

**Comment by vladikoff** [comment]
Need to update deps to fix nsp error:

```
The command "npm run test-e2e" exited with 0.
1.44s$ grunt nsp
Running "nsp" task
Warning: (+) 1 vulnerabilities found
 Name           Installed   Patched   Path                                                           More Info                              
 tough-cookie   2.2.2       >=2.3.0   fxa-auth-server@1.65.2 > request@2.65.0 > tough-cookie@2.2.2   https://nodesecurity.io/advisories/130 
 Use --force to continue.
Aborted due to warnings.
```

**Comment by rfk** [comment]
:heart: preemptive filing of follow-up issue to re-enable them

**Pull request merged**
