### PR TITLE
refactor(tests): Reorganize local tests

### LINKED ISSUE #1400: Separate local account routes tests
Our `/est/local/account_routes.js` tests are growing (over 1400+ lines) and it tests several different routes. It could be useful to separate routes into different test files to help reduce complexity of file.

### PR DESCRIPTION
**Pull request by vbudhram**
Taking a page out of Shane/Phil's book and doing technical debt Friday thingy. This PR does the following

* Makes the `local/test` match stucture of `lib`

screen shot 2017-01-27 at 10 37 19 am

* Splits the `local/test/account_routes.js` into corresponding routes making it easier to read.

Fixes #1400

### CODE REVIEW

**Comment by vbudhram** [comment]
@mozilla/fxa-devs ?

**Comment by vladikoff** [comment]
@vbudhram does it make sense to put `lib_server` into `lib/server.js`?

**Comment by philbooth** [comment]
@vbudhram how about also getting rid of the `_tests` suffix on all of the file names? It's completely redundant, they're already in a `test` directory after all.

**Comment by vladikoff** [comment]
Tests Tests Tests Tests !

**Comment by vbudhram** [comment]
@vladikoff Thanks!

**Pull request merged**
