### PR TITLE
fix(password): Remove raw token support

### LINKED ISSUE #1351: Remove support for accepting raw session token in /password/change/finish
This is a follow up to https://github.com/mozilla/fxa-content-server/issues/3875

Once this has been able to ride the trains, remove support for accepting session data from [/password/change/finish](https://github.com/mozilla/fxa-auth-server/blob/master/lib/routes/password.js#L171)

### PR DESCRIPTION
**Pull request by vbudhram**
This PR removes accepting raw session token data on password changes. Any request sending this data will receive an invalid verification code error.

Fixes #1351

### CODE REVIEW

**Comment by vbudhram** [comment]
@philbooth When you get a chance r?

**Comment by seanmonstar** [comment]
Looks right to me.

**Comment by rfk** [comment]
Is it safe to ship this in train-77, or do we need to wait a train to guard against rollbacks of the content-server code?

**Comment by vbudhram** [comment]
@rfk Correct me if I'm wrong but looks like the needed change, [fxa-js-client 1.46](https://github.com/mozilla/fxa-js-client/commit/524700e54fa105d8cf24bfee9b613733ba22164b), was merged after the tag of [train-66](https://github.com/mozilla/fxa-content-server/blob/master/CHANGELOG.md#bug-fixes). I think I might have jumped the gun with this PR, should I back it out?

**Comment by rfk** [comment]
Right, if the content-server fix isn't in train-66 we'll need to back this one out and target it for train-68

**Comment by seanmonstar** [comment]
My mistake, the related issue seemed like this was ready. Revert is up at #1396

**Pull request merged**
