### PR TITLE
feat(oauth): pass email=false when verifying oauth tokens

### LINKED ISSUE #1109: Pass email=false when verifying oauth tokens, to avoid infinite recursion
As described in https://github.com/mozilla/fxa-oauth-server/issues/352#issuecomment-155357519

### PR DESCRIPTION
**Pull request by seanmonstar**
Closes #1109

### CODE REVIEW

**Comment by rfk** [comment]
LGTM

**Comment by l-hedgehog** [comment]
If I'm reading mozilla/hapi-fxa-oauth#3 correctly, I think this should be "oauth.extra.email" instead of "oauth.email"?

**Comment by rfk** [comment]
I think you may be right, @seanmonstar can you please take a look and confirm?

**Comment by seanmonstar** [comment]
Heh, it seems that this indeed is doing nothing. Thankfully, we decided in the oauth server to not fetch the email from the auth server, so there isn't a recursive request of death. This is just causing [warnings](https://github.com/mozilla/fxa-oauth-server/blob/master/lib/routes/verify.js#L29) in the oauth server.

**Pull request merged**
