### PR TITLE
chore(git): Run a quick linting task on pre-push

### PR DESCRIPTION
**Pull request by eoger**
We did this in https://github.com/mozilla/fxa-content-server/issues/2592 and it worked out pretty well!

### CODE REVIEW

**Comment by TDA** [comment]
LGTM! +1 for the idea!

**Comment by vladikoff** [comment]
Needs a shrinkwap update with --dev

**Comment by eoger** [comment]
Should I investigate adding [npm-shrinwrap-check](https://www.npmjs.com/package/npm-shrinkwrap-check) as another pre-push check?

**Comment by vladikoff** [comment]
> Should I investigate adding npm-shrinkwrap-check as another pre-push hook?

Let's skip that for now and just land this

**Pull request merged**
