### PR TITLE
refactor(email): remove email parameter from config

### PR DESCRIPTION
**Pull request by deeptibaghel**

### CODE REVIEW

**Comment by vladikoff** [comment]
I think there might be cases where this is still in the code, one I found is at https://github.com/mozilla/fxa-auth-server/blob/master/test/local/server.js#L527

**Comment by vladikoff** [comment]
@rfk I assume this is where the extra param was sent to https://github.com/mozilla/fxa-auth-server/blob/master/lib/server.js#L250 

r? and merge. I was hoping we could add this to a point release (to speed up the oauth PRs), but maybe too risky?

**Comment by rfk** [comment]
>  I assume this is where the extra param was sent to 

Yep.

> I was hoping we could add this to a point release (to speed up the oauth PRs), but maybe too risky?

I think it's fine, risk should be pretty low.

**Comment by vladikoff** [comment]
@deeptibaghel Thank you!!

**Pull request merged**
