### PR TITLE
fix(mailer): escape json output

### PR DESCRIPTION
**Pull request by g-k**
refs: bmo bug 1320211

### CODE REVIEW

**Comment by vladikoff** [comment]
@g-k hey, could you please rebase this ?

**Comment by g-k** [comment]
Rebased.

Also, this doesn't have to go in since we have XCTO.

**Comment by vladikoff** [comment]
> Also, this doesn't have to go in since we have XCTO.

Oh? It's still to add this though, right?

**Comment by g-k** [comment]
Yeah, still nice to have this for old browsers, but if there's a
significant perf hit or it breaks something don't hesitate to roll it back.

**Comment by vladikoff** [comment]
ok!

**Comment by vladikoff** [comment]
Moved to https://github.com/mozilla/fxa-auth-server/pull/1853

**Pull request closed without merging**
