### PR TITLE
fix(config): stop using envc; interferes with docker --env-file

### PR DESCRIPTION
**Pull request by jrgm**
r? - @vladikoff, or @seanmonstar, or @vbudhram

### CODE REVIEW

**Comment by jrgm** [comment]
And I forgot to remove the .env.dev file. One sec.

**Comment by jrgm** [comment]
Note: `RESEND_BLACKOUT_PERIOD` and `TRUSTED_JKUS` no longer exist in config/index.js' schema, so they were dropped. 

I set "verifierVersion": 0, but default is 1. I forget the difference.

**Comment by jrgm** [comment]
And I checked that the config dump on `npm start` matches with either master or this branch.

**Comment by jrgm** [comment]
For the record, the reason that I'm removing this is that, if NODE_ENV='dev', `envc()` always trumps whatever environment variables you try to set with docker. i.e., configuring with explicit environment variables is not possible.

**Comment by vladikoff** [comment]
excited!

**Pull request merged**
