### PR TITLE
refactor(config): Use human-readable duration values in config

### PR DESCRIPTION
**Pull request by pdehaan**
Ref: https://github.com/mozilla/fxa-oauth-server/issues/296

### CODE REVIEW

**Comment by pdehaan** [comment]
I, like, have no idea why this imploded. :sadface:

**Comment by TDA** [comment]
You broke it Peter! 
what have you done through being a meme _591a0f7751729de874a96706e77a3e64

**Comment by rfk** [comment]
I suspect a bug in convict here.  If the duration type is specified as a string like "1000" then convict tries to parse it into a (quantity, unit) pair but fails because it doesn't contain whitespace.  /cc @zaach

**Comment by rfk** [comment]
This PR seems a lot better with this fix on the convict side: https://github.com/mozilla/node-convict/pull/87

@zaach can you please take a look and cut a new convict release if that seems sensible?

**Comment by zaach** [comment]
convict 1.0.1 is out with the bug fix.

**Comment by pdehaan** [comment]
Rebased and I _didn't_ blow up auth-server this time! \o/

r? @rfk

**Pull request merged**
