### PR TITLE
fix(sms); DRY up sms.{regions,senderIds}

### PR DESCRIPTION
**Pull request by jrgm**
r? @philbooth 

Not sure what to stuff in as plausible dummy numbers in RO and GB, but the values shouldn't matter to the actual test.

### CODE REVIEW

**Comment by jrgm** [comment]
circle-ci failed again with 
`  1) remote sms (mocked nexmo) POST /sms success:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.`

**Comment by vladikoff** [comment]
@jrgm https://github.com/mozilla/fxa-auth-server/issues/1842 @philbooth is looking into it. Restarted the thing

**Comment by philbooth** [comment]
Nice one, thanks @jrgm!

**Comment by jrgm** [comment]
Anyone know a list of intl equivalents to 18005551212?

**Pull request merged**
