### PR TITLE
feat(locale): add Arabic locale support

### PR DESCRIPTION
**Pull request by vladikoff**
100% complete https://pontoon.mozilla.org/ar/firefox-accounts/ 

@jrgm @vbudhram r?

### CODE REVIEW

**Comment by vbudhram** [comment]
LGTM 👍

Ref: https://github.com/mozilla/fxa-content-server/pull/3726

**Comment by jrgm** [comment]
Need to update for fxa-auth-server to match.

**Comment by vladikoff** [comment]
yeap. we did

**Comment by jrgm** [comment]
Ah, I see. Just was seeing a warning on this in a repo that hasn't merged this change back in.

**Pull request merged**
