### PR TITLE
Add LGTM code quality badges

### PR DESCRIPTION
**Pull request by xcorail**
Hi there!

I thought you might be interested in adding these [code quality badges](https://lgtm.com/projects/g/mozilla/fxa-auth-server/ci/#badges) to your project. They will indicate a very high code quality to potential users and contributors.
You can also check the alerts discovered by [LGTM](https://lgtm.com/projects/g/mozilla/fxa-auth-server).

N.B.: I am on the team behind LGTM.com, I'd appreciate your feedback on this initiative, whether you're interested or not, if you find time to drop me a line. Thanks.

### CODE REVIEW

**Comment by philbooth** [comment]
@xcorail, LGTM alerts this line from our repo with the warning "this expression always evaluates to true":

```js
const suggestAccountDeletion = !! bounce && bounce.bounceType
```

But it doesn't:

```
~ $ node
> let bounce = { bounceType: 'wibble' }
undefined
> !! bounce && bounce.bounceType
'wibble'
> let bounce2 = {}
undefined
> !! bounce2 && bounce2.bounceType
undefined
```

Although interestingly, the warning would have been on to something if it was only singly-negated:

```
> ! bounce && bounce.bounceType
false
> ! bounce2 && bounce2.bounceType
false
```

Anyway, just fyi, as the diagnosis seems slightly off in this case.

**Comment by xcorail** [comment]
@philbooth, thanks a lot! I will raise this to our javascript analysis team!

**Comment by xcorail** [comment]
@philbooth I got the answer. If you mouseover the alert description (the giant red box), LGTM will highlight the exact expression which is always evaluated to true. In this case, it's not the entire `&&` expression, but only `!! bounce`. So the alert says that `!! bounce` is always evaluated to true.

**Comment by xcorail** [comment]
@philbooth thanks! Note that if you want to keep this quality level, you can activate the automated code review during Pull Request: https://lgtm.com/projects/g/mozilla/fxa-auth-server/ci/ 
The same analysis will be run on the pull request and report any new problem directly in the PR.
Give it a try and let me know!
Cheers

**Pull request merged**
