### PR TITLE
fix(node 8): support for node 8 removed

### LINKED ISSUE #2958: Remove support for node 8, support 10+
We still support node 8 but our Docker images are now built using node 10. Let's drop support for node 8 and remove node-scrypt from the devDependencies list.

### PR DESCRIPTION
**Pull request by farhan787**
fixes #2958

### CODE REVIEW

**Comment by philbooth** [comment]
@farhan787, you'll also need to remove the `scrypt-hash` dependency and regenerate shrinkwrap using `npm run shrink`.

**Comment by farhan787** [comment]
@philbooth lib/crypto/password.js is using the scrypt-hash depedency then what should be the replacement for that ?

**Comment by farhan787** [comment]
@philbooth I got it!

**Comment by farhan787** [comment]
@philbooth @shane-tomlinson I request you guys to delete this PR and review #2963 
I accidentally, made a new branch issue-#2961 which was PR id, so please review this PR and delete #2961

**Pull request closed without merging**
